INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES ( 10001, 'in28minutes', 'Get AWS Certified', CURRENT_DATE(), false );

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES ( 10002, 'in28minutes', 'Get Azure Certified', CURRENT_DATE(), false );

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES ( 10003, 'ranga', 'Get GCP Certified', CURRENT_DATE(), false );

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES ( 10004, 'in28minutes', 'Learn DevOps', CURRENT_DATE(), false );